modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPLv3"

[[mods]]
modId = "quicksand"
version = "${file.jarVersion}"
displayName = "Quicksand"
authors="Moodss"
description = '''
Adds vanilla friendly quicksand to give the sandy biomes a tint of danger just like powered snow did for snowy biomes.
'''

[[dependencies.quicksand]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quicksand]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
